#+TITLE: emacs-gcc - Dockerfile for building emacs.deb with native-comp

⛔️ DEPRECATED. Consider Emacs  [[https://github.com/konstare/emacs-gcc-pgtk/][with native compilation and pure GTK]]

* Summary
This repository shows a Dockerfile to create a emacs deb package with native compilation.
The similar [[https://github.com/konstare/emacs-gcc-pgtk][repository]] shows a Dockerfile for nativecomp and pure GTK support.

** The repository is the fork of  [[https://github.com/hackenbergstefan/emacs-jit-build][the repository]], with few changes: 
1. The deb is built for  ubuntu 20.10, so no libgccjit mess.
2. no xwidgets
3. no imagemagick. Emacs now supports resizing and rotating of images without ImageMagick.
4. all =.el= files are compiled. ~make NATIVE_FULL_AOT=1~
** The package is compiled with flags:
+ --with-mailutils
+ --without-xwidgets
+ --with-modules
+ --with-native-compilation
+ --with-json
+ --without-makeinfo
+ CFLAGS="-O2 -pipe"

* Installation 1: Use [[https://github.com/konstare/emacs-gcc/actions][GitHub Actions]]
The deb package with this recipe is built by =github= and can be found in [[https://github.com/konstare/emacs-gcc/actions?query=is%3Acompleted][GitHub Actions]].


If the deb package is too old: 
1. fork the project
2. In =GitHub Actions= allow and run manually the workflow.

* Installation 2: Compile on your own computer
** Requirements
1. docker
** Compilation 
#+begin_src bash
git clone https://github.com/konstare/emacs-gcc
cd emacs-gcc
./build.sh
#+end_src
